skip = [
    "julia",
    "BugReporting", # nested rr is not supported

    # deprecated
    "NeuralNetDiffEq",
    "DiffEqBiological",
    "DiffEqMonteCarlo",
    "DiffEqPDEBase",
    "CUDAnative",
    "CUDAatomics",
    "CuArrays",
    "CUDAdrv",
    "CUDAapi",
    "AMDGPUnative",
    "ROCArrays",
    "GPUifyLoops",

    # requires binaries
    "MATLAB",               # MATLAB
    "MATLABDiffEq",         # MATLAB
    "deSolveDiffEq",        # R
    "FEniCS",               # Docker
    "ClimateMachine",       # MPI
    "MPI",                  # MPI
    "BitemporalPostgres",   # POSTGRES
    
    # requires specific environment
    "AWSS3",                # AWS secrets
    "AWSCRT",               #
    "AWSTools",             #
    "GPUInspector",         # GPU hardware
    "CUDA",                 # CUDA hardware
    "ArrayInterfaceCUDA",   #
    "NNlibCUDA",            #
    "BloqadeCUDA",          #
    "FoldsCUDA",            #
    "LinearSolveCUDA",      #
    "oneAPI",               # oneAPI hardware
    "AMDGPU",               # AMD GPU hardware
]
