name: CI
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.build_spec }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.7'
        os:
          - ubuntu-latest
        arch:
          - x64
        build_spec:
          - v1.7.0      # release from versions.json
          - nightly     # special release
          - master      # directly from Git, likely built by CI
          - master~500  # directly from Git, unlikely built by CI
    env:
      JULIA_DEBUG: PkgEval
      JULIA: ${{ matrix.build_spec }}
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
